-- =========================================================
-- ONE TAG ONE NATION - COMPLETE DATABASE PROJECT
-- Single-file version for Oracle SQL Developer
-- Location: Desktop\OneTagOneNation_DatabaseProject
-- =========================================================

SET SERVEROUTPUT ON;

-- >>> FILE: sql\01_drop_tables.sql

-- =========================================================
-- ONE TAG ONE NATION - DROP ALL TABLES
-- Run this first to reset the database
-- =========================================================

DROP TABLE ALERT_NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE FEEDBACK CASCADE CONSTRAINTS;
DROP TABLE ADMIN_LOG CASCADE CONSTRAINTS;
DROP TABLE TRANSACTION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE EXEMPTION CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_RECHARGE CASCADE CONSTRAINTS;
DROP TABLE OUT_TERMINAL CASCADE CONSTRAINTS;
DROP TABLE IN_TERMINAL CASCADE CONSTRAINTS;
DROP TABLE TERMINAL CASCADE CONSTRAINTS;
DROP TABLE LANE CASCADE CONSTRAINTS;
DROP TABLE CAMERA_SYSTEM CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_MOTORCYCLE CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_TRUCK CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_CAR_JEEP_BUS CASCADE CONSTRAINTS;
DROP TABLE VEHICLE CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_TYPE CASCADE CONSTRAINTS;
DROP TABLE DRIVER CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE ROLE CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE TOLL_PLAZA CASCADE CONSTRAINTS;
DROP TABLE HIGHWAY_UPDATE CASCADE CONSTRAINTS;
DROP TABLE HIGHWAY CASCADE CONSTRAINTS;
DROP TABLE MOTORWAY CASCADE CONSTRAINTS;
DROP TABLE SERVICE CASCADE CONSTRAINTS;



-- >>> FILE: sql\02_create_tables.sql

-- =========================================================
-- ONE TAG ONE NATION - CREATE ALL TABLES (17 CORE + ER EXTENSIONS)
-- Oracle SQL
-- =========================================================

-- =========================================================
-- 1. USERS
-- =========================================================
CREATE TABLE USERS (
    USER_ID             NUMBER PRIMARY KEY,
    NAME                VARCHAR2(100) NOT NULL,
    CNIC                VARCHAR2(15) UNIQUE NOT NULL,
    PHONE               VARCHAR2(15),
    EMAIL               VARCHAR2(100),
    PROVINCE            VARCHAR2(50),
    ADDRESS             VARCHAR2(200),
    EMERGENCY_CONTACT   VARCHAR2(15),
    IS_ACTIVE           CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
    USERNAME            VARCHAR2(50) UNIQUE,
    PASSWORD            VARCHAR2(50)
);

-- =========================================================
-- 2. ROLE & USER_ROLE (ER Diagram)
-- =========================================================
CREATE TABLE ROLE (
    ROLE_ID             NUMBER PRIMARY KEY,
    ROLE_NAME           VARCHAR2(50) NOT NULL,
    DESCRIPTION         VARCHAR2(200)
);

CREATE TABLE USER_ROLE (
    USER_ROLE_ID        NUMBER PRIMARY KEY,
    USER_ID             NUMBER NOT NULL,
    ROLE_ID             NUMBER NOT NULL,
    ASSIGNED_DATE       DATE DEFAULT SYSDATE,
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

-- =========================================================
-- 3. DRIVER
-- =========================================================
CREATE TABLE DRIVER (
    DRIVER_CNIC         VARCHAR2(15) PRIMARY KEY,
    DRIVER_NAME         VARCHAR2(100) NOT NULL,
    LICENSE_NO          VARCHAR2(30) UNIQUE,
    DRIVER_PHONE        VARCHAR2(15),
    LICENSE_EXPIRY      DATE
);

-- =========================================================
-- 4. VEHICLE_TYPE
-- =========================================================
CREATE TABLE VEHICLE_TYPE (
    TYPE_ID             NUMBER PRIMARY KEY,
    VEHICLE_CLASS       VARCHAR2(50) NOT NULL,
    TOLL_RATE_PER_KM    NUMBER(10,2) NOT NULL
);

-- =========================================================
-- 5. VEHICLE (Supertype)
-- =========================================================
CREATE TABLE VEHICLE (
    VEHICLE_ID          NUMBER PRIMARY KEY,
    USER_ID             NUMBER NOT NULL,
    DRIVER_CNIC         VARCHAR2(15),
    TYPE_ID             NUMBER NOT NULL,
    PLATE_NUMBER        VARCHAR2(20) UNIQUE NOT NULL,
    MODEL               VARCHAR2(50),
    COMPANY             VARCHAR2(50),
    COLOR               VARCHAR2(30),
    IS_BLACKLISTED      CHAR(1) DEFAULT 'N' CHECK (IS_BLACKLISTED IN ('Y','N')),
    CONSTRAINT FK_V_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_V_DRIVER FOREIGN KEY (DRIVER_CNIC) REFERENCES DRIVER(DRIVER_CNIC),
    CONSTRAINT FK_V_TYPE FOREIGN KEY (TYPE_ID) REFERENCES VEHICLE_TYPE(TYPE_ID)
);

-- Vehicle ISA Subtypes (ER Diagram)
CREATE TABLE VEHICLE_CAR_JEEP_BUS (
    VEHICLE_ID          NUMBER PRIMARY KEY,
    SEATS               NUMBER,
    AXLES               NUMBER DEFAULT 2,
    CONSTRAINT FK_VCJB_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

CREATE TABLE VEHICLE_TRUCK (
    VEHICLE_ID          NUMBER PRIMARY KEY,
    NO_OF_AXLES         NUMBER NOT NULL,
    LOAD_CAPACITY       NUMBER(10,2),
    CONSTRAINT FK_VT_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

CREATE TABLE VEHICLE_MOTORCYCLE (
    VEHICLE_ID          NUMBER PRIMARY KEY,
    ENGINE_CAPACITY     NUMBER,
    CONSTRAINT FK_VM_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

-- =========================================================
-- 6. TAG
-- =========================================================
CREATE TABLE TAG (
    TAG_ID              NUMBER PRIMARY KEY,
    USER_ID             NUMBER NOT NULL,
    VEHICLE_ID          NUMBER NOT NULL,
    BALANCE             NUMBER(10,2) DEFAULT 0,
    RESERVE_BALANCE     NUMBER(10,2) DEFAULT 0,
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',
    ISSUE_DATE          DATE DEFAULT SYSDATE,
    EXPIRY_DATE         DATE,
    CONSTRAINT FK_TAG_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_TAG_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

-- =========================================================
-- 7. MOTORWAY & HIGHWAY (ER Diagram hierarchy)
-- =========================================================
CREATE TABLE MOTORWAY (
    MOTORWAY_ID         NUMBER PRIMARY KEY,
    MOTORWAY_NAME       VARCHAR2(100) NOT NULL,
    START_CITY          VARCHAR2(100),
    END_CITY            VARCHAR2(100),
    TOTAL_DISTANCE_KM   NUMBER(10,2)
);

CREATE TABLE HIGHWAY (
    HIGHWAY_ID          NUMBER PRIMARY KEY,
    MOTORWAY_ID         NUMBER NOT NULL,
    HIGHWAY_NAME        VARCHAR2(100) NOT NULL,
    SECTION_NAME        VARCHAR2(100),
    DIRECTION           VARCHAR2(20),
    START_LOCATION      VARCHAR2(100),
    END_LOCATION        VARCHAR2(100),
    TOTAL_DISTANCE      NUMBER(10,2),
    CONSTRAINT FK_HW_MOTORWAY FOREIGN KEY (MOTORWAY_ID) REFERENCES MOTORWAY(MOTORWAY_ID)
);

-- =========================================================
-- 8. HIGHWAY_UPDATE
-- =========================================================
CREATE TABLE HIGHWAY_UPDATE (
    UPDATE_ID           NUMBER PRIMARY KEY,
    HIGHWAY_ID          NUMBER NOT NULL,
    SURCHARGE           NUMBER(10,2) DEFAULT 0,
    UPDATE_DATE         DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HU_HIGHWAY FOREIGN KEY (HIGHWAY_ID) REFERENCES HIGHWAY(HIGHWAY_ID)
);

-- =========================================================
-- 9. SERVICE
-- =========================================================
CREATE TABLE SERVICE (
    SERVICE_ID          NUMBER PRIMARY KEY,
    SERVICE_NAME        VARCHAR2(100) NOT NULL,
    SERVICE_TYPE        VARCHAR2(50),
    TOLL_RATE_PER_KM    NUMBER(10,2),
    BASE_RATE_PER_KM    NUMBER(10,2),
    SURCHARGE_RATE      NUMBER(10,2) DEFAULT 0,
    EFFECTIVE_FROM      DATE DEFAULT SYSDATE
);

-- =========================================================
-- 10. TOLL_PLAZA
-- =========================================================
CREATE TABLE TOLL_PLAZA (
    PLAZA_ID            NUMBER PRIMARY KEY,
    HIGHWAY_ID          NUMBER NOT NULL,
    SERVICE_ID          NUMBER,
    PLAZA_NAME          VARCHAR2(100) NOT NULL,
    LOCATION            VARCHAR2(100),
    PROVINCE            VARCHAR2(50),
    LATITUDE            NUMBER(10,6),
    LONGITUDE           NUMBER(10,6),
    EXIT_NO             VARCHAR2(20),
    MILE_NO             NUMBER(10,2),
    CONSTRAINT FK_TP_HIGHWAY FOREIGN KEY (HIGHWAY_ID) REFERENCES HIGHWAY(HIGHWAY_ID),
    CONSTRAINT FK_TP_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);

-- =========================================================
-- 11. TERMINAL (IN/OUT) - ER Diagram
-- =========================================================
CREATE TABLE TERMINAL (
    TERMINAL_ID         NUMBER PRIMARY KEY,
    PLAZA_ID            NUMBER NOT NULL,
    TERMINAL_NAME       VARCHAR2(100),
    TERMINAL_TYPE       VARCHAR2(10) CHECK (TERMINAL_TYPE IN ('IN','OUT')),
    MILE_NO             NUMBER(10,2),
    DISTANCE_FROM_PREV  NUMBER(10,2),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT FK_TERM_PLAZA FOREIGN KEY (PLAZA_ID) REFERENCES TOLL_PLAZA(PLAZA_ID)
);

CREATE TABLE IN_TERMINAL (
    TERMINAL_ID         NUMBER PRIMARY KEY,
    LANE_NO             NUMBER,
    READER_IP           VARCHAR2(50),
    CAMERA_IP           VARCHAR2(50),
    CONSTRAINT FK_IN_TERM FOREIGN KEY (TERMINAL_ID) REFERENCES TERMINAL(TERMINAL_ID)
);

CREATE TABLE OUT_TERMINAL (
    TERMINAL_ID         NUMBER PRIMARY KEY,
    LANE_NO             NUMBER,
    READER_IP           VARCHAR2(50),
    CAMERA_IP           VARCHAR2(50),
    CONSTRAINT FK_OUT_TERM FOREIGN KEY (TERMINAL_ID) REFERENCES TERMINAL(TERMINAL_ID)
);

-- =========================================================
-- 12. EMPLOYEE
-- =========================================================
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID         NUMBER PRIMARY KEY,
    EMPLOYEE_NAME       VARCHAR2(100) NOT NULL,
    PHONE               VARCHAR2(15),
    DESIGNATION         VARCHAR2(50),
    PLAZA_ID            NUMBER,
    CONSTRAINT FK_EMP_PLAZA FOREIGN KEY (PLAZA_ID) REFERENCES TOLL_PLAZA(PLAZA_ID)
);

-- =========================================================
-- 13. CAMERA_SYSTEM
-- =========================================================
CREATE TABLE CAMERA_SYSTEM (
    CAMERA_ID           NUMBER PRIMARY KEY,
    PLAZA_ID            NUMBER NOT NULL,
    CAMERA_LOCATION     VARCHAR2(100),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT FK_CAM_PLAZA FOREIGN KEY (PLAZA_ID) REFERENCES TOLL_PLAZA(PLAZA_ID)
);

-- =========================================================
-- 14. LANE
-- =========================================================
CREATE TABLE LANE (
    LANE_ID             NUMBER PRIMARY KEY,
    PLAZA_ID            NUMBER NOT NULL,
    LANE_TYPE           VARCHAR2(50),
    STATUS              VARCHAR2(20) DEFAULT 'OPEN',
    CONSTRAINT FK_LANE_PLAZA FOREIGN KEY (PLAZA_ID) REFERENCES TOLL_PLAZA(PLAZA_ID)
);

-- =========================================================
-- 15. EXEMPTION (ER Diagram)
-- =========================================================
CREATE TABLE EXEMPTION (
    EXEMPTION_ID        NUMBER PRIMARY KEY,
    USER_ID             NUMBER NOT NULL,
    PLAZA_ID            NUMBER,
    REASON              VARCHAR2(200),
    START_DATE          DATE,
    END_DATE            DATE,
    DISCOUNT_TYPE       VARCHAR2(20),
    DISCOUNT_VALUE      NUMBER(10,2),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT FK_EX_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_EX_PLAZA FOREIGN KEY (PLAZA_ID) REFERENCES TOLL_PLAZA(PLAZA_ID)
);

-- =========================================================
-- 16. TRANSACTION_HISTORY (Enhanced per ER Diagram)
-- =========================================================
CREATE TABLE TRANSACTION_HISTORY (
    TRANSACTION_ID      NUMBER PRIMARY KEY,
    TAG_ID              NUMBER NOT NULL,
    SERVICE_ID          NUMBER,
    PLAZA_ID            NUMBER,
    ENTRY_TERMINAL_ID   NUMBER,
    EXIT_TERMINAL_ID    NUMBER,
    ENTRY_TIME          TIMESTAMP,
    EXIT_TIME           TIMESTAMP,
    DISTANCE_TRAVELLED  NUMBER(10,2),
    TOLL_RATE_PER_KM    NUMBER(10,2),
    BASE_TOLL           NUMBER(10,2),
    SURCHARGE           NUMBER(10,2) DEFAULT 0,
    EXEMPTION_DISCOUNT  NUMBER(10,2) DEFAULT 0,
    TOTAL_AMOUNT        NUMBER(10,2),
    DEDUCTED_BALANCE    NUMBER(10,2),
    STATUS              VARCHAR2(20) DEFAULT 'COMPLETED',
    DATE_CLASS          VARCHAR2(20),
    TRANSACTION_DATE    DATE DEFAULT SYSDATE,
    CONSTRAINT FK_TH_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID),
    CONSTRAINT FK_TH_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
    CONSTRAINT FK_TH_PLAZA FOREIGN KEY (PLAZA_ID) REFERENCES TOLL_PLAZA(PLAZA_ID),
    CONSTRAINT FK_TH_ENTRY FOREIGN KEY (ENTRY_TERMINAL_ID) REFERENCES TERMINAL(TERMINAL_ID),
    CONSTRAINT FK_TH_EXIT FOREIGN KEY (EXIT_TERMINAL_ID) REFERENCES TERMINAL(TERMINAL_ID)
);

-- =========================================================
-- 17. PAYMENT
-- =========================================================
CREATE TABLE PAYMENT (
    PAYMENT_ID          NUMBER PRIMARY KEY,
    TAG_ID              NUMBER NOT NULL,
    AMOUNT              NUMBER(10,2) NOT NULL,
    PAYMENT_DATE        DATE DEFAULT SYSDATE,
    PAYMENT_METHOD      VARCHAR2(50),
    BANK_REF            VARCHAR2(50),
    STATUS              VARCHAR2(20) DEFAULT 'SUCCESS',
    CONSTRAINT FK_PAY_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID)
);

-- =========================================================
-- 18. ACCOUNT_RECHARGE
-- =========================================================
CREATE TABLE ACCOUNT_RECHARGE (
    RECHARGE_ID         NUMBER PRIMARY KEY,
    TAG_ID              NUMBER NOT NULL,
    RECHARGE_AMOUNT     NUMBER(10,2) NOT NULL,
    RECHARGE_DATE       DATE DEFAULT SYSDATE,
    METHOD              VARCHAR2(50),
    BANK_REF            VARCHAR2(50),
    STATUS              VARCHAR2(20) DEFAULT 'SUCCESS',
    CONSTRAINT FK_AR_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID)
);

-- =========================================================
-- 19. FEEDBACK
-- =========================================================
CREATE TABLE FEEDBACK (
    FEEDBACK_ID         NUMBER PRIMARY KEY,
    USER_ID             NUMBER NOT NULL,
    COMMENTS            VARCHAR2(300),
    RATING              NUMBER CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT FK_FB_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- =========================================================
-- 20. ALERT_NOTIFICATION
-- =========================================================
CREATE TABLE ALERT_NOTIFICATION (
    ALERT_ID            NUMBER PRIMARY KEY,
    TAG_ID              NUMBER NOT NULL,
    ALERT_MESSAGE       VARCHAR2(200),
    ALERT_DATE          DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ALERT_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID)
);

-- =========================================================
-- 21. ADMIN_LOG (Audit trail)
-- =========================================================
CREATE TABLE ADMIN_LOG (
    LOG_ID              NUMBER PRIMARY KEY,
    ADMIN_USER_ID       NUMBER,
    ACTION_TYPE         VARCHAR2(50),
    ACTION_DETAIL       VARCHAR2(500),
    LOG_DATE            TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LOG_USER FOREIGN KEY (ADMIN_USER_ID) REFERENCES USERS(USER_ID)
);



-- >>> FILE: sql\03_insert_data.sql

-- =========================================================
-- ONE TAG ONE NATION - INSERTIONS USING DUAL
-- =========================================================

-- USERS
INSERT INTO USERS SELECT 1,'Maryam Shakil','37405-1234567-1','03001234567','maryam@gmail.com','Punjab','Taxila','03009998888','Y','maryam','123' FROM DUAL;
INSERT INTO USERS SELECT 2,'Ayesha Waqar','37405-7654321-2','03111234567','ayesha@gmail.com','ICT','Islamabad','03119998888','Y','ayesha','123' FROM DUAL;
INSERT INTO USERS SELECT 3,'Admin User','37405-9999999-9','03451234567','admin@otn.gov.pk','ICT','Islamabad','03459998888','Y','admin','admin123' FROM DUAL;

-- ROLE
INSERT INTO ROLE SELECT 1,'CUSTOMER','Registered vehicle owner' FROM DUAL;
INSERT INTO ROLE SELECT 2,'ADMIN','System administrator' FROM DUAL;
INSERT INTO ROLE SELECT 3,'PLAZA_MANAGER','Toll plaza manager' FROM DUAL;

-- USER_ROLE
INSERT INTO USER_ROLE SELECT 1,1,1,SYSDATE FROM DUAL;
INSERT INTO USER_ROLE SELECT 2,2,1,SYSDATE FROM DUAL;
INSERT INTO USER_ROLE SELECT 3,3,2,SYSDATE FROM DUAL;

-- DRIVER
INSERT INTO DRIVER SELECT '37405-1111111-1','Ali Khan','LIC1001','03211234567',TO_DATE('2028-12-31','YYYY-MM-DD') FROM DUAL;
INSERT INTO DRIVER SELECT '37405-2222222-2','Hassan Raza','LIC1002','03221234567',TO_DATE('2027-06-30','YYYY-MM-DD') FROM DUAL;

-- VEHICLE_TYPE (Rates per ER Diagram)
INSERT INTO VEHICLE_TYPE SELECT 1,'Car',5.00 FROM DUAL;
INSERT INTO VEHICLE_TYPE SELECT 2,'Jeep',7.00 FROM DUAL;
INSERT INTO VEHICLE_TYPE SELECT 3,'Bus',8.00 FROM DUAL;
INSERT INTO VEHICLE_TYPE SELECT 4,'Truck 2 Axle',12.00 FROM DUAL;
INSERT INTO VEHICLE_TYPE SELECT 5,'Truck 3 Axle',18.00 FROM DUAL;
INSERT INTO VEHICLE_TYPE SELECT 6,'Truck 4+ Axle',25.00 FROM DUAL;
INSERT INTO VEHICLE_TYPE SELECT 7,'Motorcycle',3.00 FROM DUAL;

-- VEHICLE
INSERT INTO VEHICLE SELECT 101,1,'37405-1111111-1',1,'LEA-1234','Corolla','Toyota','White','N' FROM DUAL;
INSERT INTO VEHICLE SELECT 102,2,'37405-2222222-2',3,'ISB-5678','Coaster','Hino','Blue','N' FROM DUAL;
INSERT INTO VEHICLE SELECT 103,1,NULL,4,'RWP-9012','Truck','Hino','Red','N' FROM DUAL;

-- VEHICLE SUBTYPES (ISA)
INSERT INTO VEHICLE_CAR_JEEP_BUS SELECT 101,5,2 FROM DUAL;
INSERT INTO VEHICLE_CAR_JEEP_BUS SELECT 102,45,2 FROM DUAL;
INSERT INTO VEHICLE_TRUCK SELECT 103,2,5000 FROM DUAL;

-- TAG
INSERT INTO TAG SELECT 1001,1,101,5000,500,'ACTIVE',SYSDATE,ADD_MONTHS(SYSDATE,60) FROM DUAL;
INSERT INTO TAG SELECT 1002,2,102,8000,800,'ACTIVE',SYSDATE,ADD_MONTHS(SYSDATE,60) FROM DUAL;
INSERT INTO TAG SELECT 1003,1,103,3000,300,'ACTIVE',SYSDATE,ADD_MONTHS(SYSDATE,60) FROM DUAL;

-- MOTORWAY
INSERT INTO MOTORWAY SELECT 1,'M1 Motorway','Islamabad','Peshawar',155 FROM DUAL;
INSERT INTO MOTORWAY SELECT 2,'M2 Motorway','Lahore','Islamabad',367 FROM DUAL;

-- HIGHWAY
INSERT INTO HIGHWAY SELECT 1,1,'M1 North Section','Islamabad-Peshawar','Northbound','Islamabad','Peshawar',155 FROM DUAL;
INSERT INTO HIGHWAY SELECT 2,2,'M2 Main Section','Lahore-Islamabad','Southbound','Lahore','Islamabad',367 FROM DUAL;

-- HIGHWAY_UPDATE
INSERT INTO HIGHWAY_UPDATE SELECT 1,1,50,SYSDATE FROM DUAL;
INSERT INTO HIGHWAY_UPDATE SELECT 2,2,30,SYSDATE FROM DUAL;

-- SERVICE
INSERT INTO SERVICE SELECT 1,'Normal Toll','STANDARD',5.00,5.00,0,SYSDATE FROM DUAL;
INSERT INTO SERVICE SELECT 2,'Peak Hour Toll','PEAK',6.00,5.00,1.00,SYSDATE FROM DUAL;

-- TOLL_PLAZA
INSERT INTO TOLL_PLAZA SELECT 1,1,1,'Islamabad Toll Plaza','Islamabad','ICT',33.6844,73.0479,'E1',0 FROM DUAL;
INSERT INTO TOLL_PLAZA SELECT 2,1,1,'Burhan Toll Plaza','Burhan','Punjab',33.8000,72.9000,'E5',45 FROM DUAL;
INSERT INTO TOLL_PLAZA SELECT 3,2,1,'Bhera Toll Plaza','Bhera','Punjab',32.4833,72.9167,'E12',120 FROM DUAL;

-- TERMINAL
INSERT INTO TERMINAL SELECT 1,1,'Islamabad Entry','IN',0,0,'ACTIVE' FROM DUAL;
INSERT INTO TERMINAL SELECT 2,1,'Islamabad Exit','OUT',25,25,'ACTIVE' FROM DUAL;
INSERT INTO TERMINAL SELECT 3,2,'Burhan Entry','IN',45,20,'ACTIVE' FROM DUAL;
INSERT INTO TERMINAL SELECT 4,2,'Burhan Exit','OUT',70,25,'ACTIVE' FROM DUAL;

-- IN_TERMINAL / OUT_TERMINAL
INSERT INTO IN_TERMINAL SELECT 1,1,'192.168.1.10','192.168.1.20' FROM DUAL;
INSERT INTO IN_TERMINAL SELECT 3,2,'192.168.2.10','192.168.2.20' FROM DUAL;
INSERT INTO OUT_TERMINAL SELECT 2,1,'192.168.1.11','192.168.1.21' FROM DUAL;
INSERT INTO OUT_TERMINAL SELECT 4,2,'192.168.2.11','192.168.2.21' FROM DUAL;

-- EMPLOYEE
INSERT INTO EMPLOYEE SELECT 1,'Usman Tariq','03331234567','Manager',1 FROM DUAL;
INSERT INTO EMPLOYEE SELECT 2,'Sara Ahmed','03341234567','Operator',2 FROM DUAL;

-- CAMERA_SYSTEM
INSERT INTO CAMERA_SYSTEM SELECT 1,1,'Entry Gate','ACTIVE' FROM DUAL;
INSERT INTO CAMERA_SYSTEM SELECT 2,1,'Exit Gate','ACTIVE' FROM DUAL;
INSERT INTO CAMERA_SYSTEM SELECT 3,2,'Entry Gate','ACTIVE' FROM DUAL;

-- LANE
INSERT INTO LANE SELECT 1,1,'FASTAG','OPEN' FROM DUAL;
INSERT INTO LANE SELECT 2,1,'CASH','OPEN' FROM DUAL;
INSERT INTO LANE SELECT 3,2,'FASTAG','OPEN' FROM DUAL;

-- EXEMPTION
INSERT INTO EXEMPTION SELECT 1,1,1,'Government Official','01-JAN-2026','31-DEC-2026','PERCENT',50,'ACTIVE' FROM DUAL;

-- TRANSACTION_HISTORY
INSERT INTO TRANSACTION_HISTORY SELECT 1,1001,1,1,1,2,SYSTIMESTAMP-INTERVAL '2' HOUR,SYSTIMESTAMP,25,5.00,125,0,0,125,125,'COMPLETED','WEEKDAY',SYSDATE FROM DUAL;
INSERT INTO TRANSACTION_HISTORY SELECT 2,1002,1,2,3,4,SYSTIMESTAMP-INTERVAL '1' DAY,SYSTIMESTAMP-INTERVAL '20' HOUR,25,8.00,200,0,0,200,200,'COMPLETED','WEEKDAY',SYSDATE-1 FROM DUAL;

-- PAYMENT
INSERT INTO PAYMENT SELECT 1,1001,2000,SYSDATE,'JazzCash','JC-REF-001','SUCCESS' FROM DUAL;
INSERT INTO PAYMENT SELECT 2,1002,5000,SYSDATE,'EasyPaisa','EP-REF-002','SUCCESS' FROM DUAL;

-- ACCOUNT_RECHARGE
INSERT INTO ACCOUNT_RECHARGE SELECT 1,1001,3000,SYSDATE,'Bank Transfer','BT-001','SUCCESS' FROM DUAL;
INSERT INTO ACCOUNT_RECHARGE SELECT 2,1003,2000,SYSDATE,'JazzCash','JC-002','SUCCESS' FROM DUAL;

-- FEEDBACK
INSERT INTO FEEDBACK SELECT 1,1,'Excellent Toll Service',5 FROM DUAL;
INSERT INTO FEEDBACK SELECT 2,2,'Fast and smooth passage',4 FROM DUAL;

-- ALERT_NOTIFICATION
INSERT INTO ALERT_NOTIFICATION SELECT 1,1001,'Low Balance Alert',SYSDATE FROM DUAL;
INSERT INTO ALERT_NOTIFICATION SELECT 2,1003,'Tag Expiring Soon',SYSDATE FROM DUAL;

-- ADMIN_LOG
INSERT INTO ADMIN_LOG SELECT 1,3,'LOGIN','Admin logged into system',SYSTIMESTAMP FROM DUAL;
INSERT INTO ADMIN_LOG SELECT 2,3,'RATE_UPDATE','Updated toll rates for M1',SYSTIMESTAMP FROM DUAL;

COMMIT;



-- >>> FILE: sql\04_sequences.sql

-- =========================================================
-- ONE TAG ONE NATION - SEQUENCES
-- =========================================================

CREATE SEQUENCE USER_SEQ           START WITH 4   INCREMENT BY 1;
CREATE SEQUENCE ROLE_SEQ           START WITH 4   INCREMENT BY 1;
CREATE SEQUENCE VEHICLE_SEQ        START WITH 104 INCREMENT BY 1;
CREATE SEQUENCE TAG_SEQ            START WITH 1004 INCREMENT BY 1;
CREATE SEQUENCE TRANSACTION_SEQ    START WITH 3   INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_SEQ        START WITH 3   INCREMENT BY 1;
CREATE SEQUENCE RECHARGE_SEQ       START WITH 3   INCREMENT BY 1;
CREATE SEQUENCE FEEDBACK_SEQ       START WITH 3   INCREMENT BY 1;
CREATE SEQUENCE ALERT_SEQ          START WITH 3   INCREMENT BY 1;
CREATE SEQUENCE EXEMPTION_SEQ      START WITH 2   INCREMENT BY 1;
CREATE SEQUENCE ADMIN_LOG_SEQ      START WITH 3   INCREMENT BY 1;



-- >>> FILE: sql\05_views.sql

-- =========================================================
-- ONE TAG ONE NATION - VIEWS
-- =========================================================

CREATE OR REPLACE VIEW VEHICLE_TAG_DETAILS AS
SELECT
    U.NAME              AS OWNER_NAME,
    U.CNIC              AS OWNER_CNIC,
    V.PLATE_NUMBER,
    VT.VEHICLE_CLASS,
    VT.TOLL_RATE_PER_KM,
    T.TAG_ID,
    T.BALANCE,
    T.RESERVE_BALANCE,
    T.STATUS            AS TAG_STATUS
FROM VEHICLE V
JOIN TAG T ON V.VEHICLE_ID = T.VEHICLE_ID
JOIN USERS U ON V.USER_ID = U.USER_ID
JOIN VEHICLE_TYPE VT ON V.TYPE_ID = VT.TYPE_ID;

CREATE OR REPLACE VIEW TRANSACTION_SUMMARY AS
SELECT
    TH.TRANSACTION_ID,
    T.TAG_ID,
    V.PLATE_NUMBER,
    TP.PLAZA_NAME,
    TH.DISTANCE_TRAVELLED,
    TH.BASE_TOLL,
    TH.SURCHARGE,
    TH.EXEMPTION_DISCOUNT,
    TH.TOTAL_AMOUNT,
    TH.TRANSACTION_DATE,
    TH.STATUS
FROM TRANSACTION_HISTORY TH
JOIN TAG T ON TH.TAG_ID = T.TAG_ID
JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
JOIN TOLL_PLAZA TP ON TH.PLAZA_ID = TP.PLAZA_ID;

CREATE OR REPLACE VIEW LOW_BALANCE_TAGS AS
SELECT
    T.TAG_ID,
    V.PLATE_NUMBER,
    U.NAME,
    U.PHONE,
    T.BALANCE
FROM TAG T
JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
JOIN USERS U ON T.USER_ID = U.USER_ID
WHERE T.BALANCE < 500
  AND T.STATUS = 'ACTIVE';

CREATE OR REPLACE VIEW PLAZA_EMPLOYEE_VIEW AS
SELECT
    TP.PLAZA_NAME,
    TP.LOCATION,
    E.EMPLOYEE_NAME,
    E.DESIGNATION,
    E.PHONE
FROM TOLL_PLAZA TP
LEFT JOIN EMPLOYEE E ON TP.PLAZA_ID = E.PLAZA_ID;



-- >>> FILE: sql\06_procedures_functions.sql

-- =========================================================
-- ONE TAG ONE NATION - PROCEDURES & FUNCTIONS
-- Toll Calculation per ER Diagram:
--   Distance = Exit MileNo - Entry MileNo
--   Base Toll = Distance x TollRatePerKm
--   Total Toll = Base Toll + Surcharge - Exemption Discount
--   Final Payable = MAX(Total Toll, 0)
-- =========================================================

-- Function: Get tag balance
CREATE OR REPLACE FUNCTION GET_BALANCE(P_TAG NUMBER)
RETURN NUMBER
IS
    V_BALANCE NUMBER;
BEGIN
    SELECT BALANCE INTO V_BALANCE
    FROM TAG WHERE TAG_ID = P_TAG;
    RETURN V_BALANCE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/

-- Function: Calculate toll amount
CREATE OR REPLACE FUNCTION CALCULATE_TOLL(
    P_ENTRY_MILE    NUMBER,
    P_EXIT_MILE     NUMBER,
    P_RATE_PER_KM   NUMBER,
    P_SURCHARGE     NUMBER DEFAULT 0,
    P_DISCOUNT      NUMBER DEFAULT 0
)
RETURN NUMBER
IS
    V_DISTANCE      NUMBER;
    V_BASE_TOLL     NUMBER;
    V_TOTAL         NUMBER;
BEGIN
    V_DISTANCE  := GREATEST(P_EXIT_MILE - P_ENTRY_MILE, 0);
    V_BASE_TOLL := V_DISTANCE * P_RATE_PER_KM;
    V_TOTAL     := V_BASE_TOLL + NVL(P_SURCHARGE,0) - NVL(P_DISCOUNT,0);
    RETURN GREATEST(V_TOTAL, 0);
END;
/

-- Procedure: Simple toll deduction
CREATE OR REPLACE PROCEDURE DEDUCT_TOLL(
    P_TAG_ID    NUMBER,
    P_AMOUNT    NUMBER
)
IS
BEGIN
    UPDATE TAG
    SET BALANCE = BALANCE - P_AMOUNT
    WHERE TAG_ID = P_TAG_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Tag not found: ' || P_TAG_ID);
    END IF;

    DBMS_OUTPUT.PUT_LINE('Toll deducted: ' || P_AMOUNT || ' from Tag ' || P_TAG_ID);
END;
/

-- Procedure: Full toll transaction flow (ER Diagram)
CREATE OR REPLACE PROCEDURE PROCESS_TOLL_TRANSACTION(
    P_TAG_ID            NUMBER,
    P_SERVICE_ID        NUMBER,
    P_PLAZA_ID          NUMBER,
    P_ENTRY_TERMINAL    NUMBER,
    P_EXIT_TERMINAL     NUMBER,
    P_ENTRY_TIME        TIMESTAMP,
    P_EXIT_TIME         TIMESTAMP
)
IS
    V_ENTRY_MILE        NUMBER;
    V_EXIT_MILE         NUMBER;
    V_RATE              NUMBER;
    V_SURCHARGE         NUMBER;
    V_DISCOUNT          NUMBER;
    V_DISTANCE          NUMBER;
    V_BASE_TOLL         NUMBER;
    V_TOTAL             NUMBER;
    V_BALANCE           NUMBER;
    V_USER_ID           NUMBER;
    V_TXN_ID            NUMBER;
BEGIN
    -- Get mile markers from terminals
    SELECT MILE_NO INTO V_ENTRY_MILE FROM TERMINAL WHERE TERMINAL_ID = P_ENTRY_TERMINAL;
    SELECT MILE_NO INTO V_EXIT_MILE FROM TERMINAL WHERE TERMINAL_ID = P_EXIT_TERMINAL;

    -- Get vehicle rate from tag -> vehicle -> vehicle_type
    SELECT VT.TOLL_RATE_PER_KM, T.USER_ID, T.BALANCE
    INTO V_RATE, V_USER_ID, V_BALANCE
    FROM TAG T
    JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
    JOIN VEHICLE_TYPE VT ON V.TYPE_ID = VT.TYPE_ID
    WHERE T.TAG_ID = P_TAG_ID;

    -- Get surcharge from highway update (latest)
    BEGIN
        SELECT NVL(HU.SURCHARGE, 0) INTO V_SURCHARGE
        FROM TOLL_PLAZA TP
        JOIN HIGHWAY_UPDATE HU ON TP.HIGHWAY_ID = HU.HIGHWAY_ID
        WHERE TP.PLAZA_ID = P_PLAZA_ID
        ORDER BY HU.UPDATE_DATE DESC
        FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN V_SURCHARGE := 0;
    END;

    -- Get exemption discount if applicable
    BEGIN
        SELECT
            CASE E.DISCOUNT_TYPE
                WHEN 'PERCENT' THEN (V_EXIT_MILE - V_ENTRY_MILE) * V_RATE * E.DISCOUNT_VALUE / 100
                WHEN 'FIXED'   THEN E.DISCOUNT_VALUE
                ELSE 0
            END
        INTO V_DISCOUNT
        FROM EXEMPTION E
        WHERE E.USER_ID = V_USER_ID
          AND (E.PLAZA_ID = P_PLAZA_ID OR E.PLAZA_ID IS NULL)
          AND E.STATUS = 'ACTIVE'
          AND SYSDATE BETWEEN E.START_DATE AND E.END_DATE
        FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN V_DISCOUNT := 0;
    END;

    -- Calculate toll
    V_DISTANCE  := GREATEST(V_EXIT_MILE - V_ENTRY_MILE, 0);
    V_BASE_TOLL := V_DISTANCE * V_RATE;
    V_TOTAL     := GREATEST(V_BASE_TOLL + V_SURCHARGE - NVL(V_DISCOUNT,0), 0);

    IF V_BALANCE < V_TOTAL THEN
        RAISE_APPLICATION_ERROR(-20002, 'Insufficient balance. Required: ' || V_TOTAL || ', Available: ' || V_BALANCE);
    END IF;

    -- Deduct balance
    UPDATE TAG SET BALANCE = BALANCE - V_TOTAL WHERE TAG_ID = P_TAG_ID;

    -- Record transaction
    SELECT TRANSACTION_SEQ.NEXTVAL INTO V_TXN_ID FROM DUAL;

    INSERT INTO TRANSACTION_HISTORY (
        TRANSACTION_ID, TAG_ID, SERVICE_ID, PLAZA_ID,
        ENTRY_TERMINAL_ID, EXIT_TERMINAL_ID,
        ENTRY_TIME, EXIT_TIME,
        DISTANCE_TRAVELLED, TOLL_RATE_PER_KM,
        BASE_TOLL, SURCHARGE, EXEMPTION_DISCOUNT,
        TOTAL_AMOUNT, DEDUCTED_BALANCE, STATUS, TRANSACTION_DATE
    ) VALUES (
        V_TXN_ID, P_TAG_ID, P_SERVICE_ID, P_PLAZA_ID,
        P_ENTRY_TERMINAL, P_EXIT_TERMINAL,
        P_ENTRY_TIME, P_EXIT_TIME,
        V_DISTANCE, V_RATE,
        V_BASE_TOLL, V_SURCHARGE, NVL(V_DISCOUNT,0),
        V_TOTAL, V_TOTAL, 'COMPLETED', SYSDATE
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Transaction ' || V_TXN_ID || ' completed. Amount: ' || V_TOTAL);
END;
/

-- Procedure: Recharge tag balance
CREATE OR REPLACE PROCEDURE RECHARGE_TAG(
    P_TAG_ID        NUMBER,
    P_AMOUNT        NUMBER,
    P_METHOD        VARCHAR2 DEFAULT 'Cash',
    P_BANK_REF      VARCHAR2 DEFAULT NULL
)
IS
    V_RECHARGE_ID   NUMBER;
BEGIN
    UPDATE TAG SET BALANCE = BALANCE + P_AMOUNT WHERE TAG_ID = P_TAG_ID;

    SELECT RECHARGE_SEQ.NEXTVAL INTO V_RECHARGE_ID FROM DUAL;

    INSERT INTO ACCOUNT_RECHARGE (RECHARGE_ID, TAG_ID, RECHARGE_AMOUNT, RECHARGE_DATE, METHOD, BANK_REF, STATUS)
    VALUES (V_RECHARGE_ID, P_TAG_ID, P_AMOUNT, SYSDATE, P_METHOD, P_BANK_REF, 'SUCCESS');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Recharge successful. New balance: ' || GET_BALANCE(P_TAG_ID));
END;
/



-- >>> FILE: sql\07_triggers.sql

-- =========================================================
-- ONE TAG ONE NATION - TRIGGERS
-- =========================================================

-- Low balance warning on tag update
CREATE OR REPLACE TRIGGER LOW_BALANCE_TRIGGER
AFTER UPDATE OF BALANCE ON TAG
FOR EACH ROW
BEGIN
    IF :NEW.BALANCE < 500 AND :NEW.BALANCE >= 0 THEN
        INSERT INTO ALERT_NOTIFICATION (ALERT_ID, TAG_ID, ALERT_MESSAGE, ALERT_DATE)
        VALUES (ALERT_SEQ.NEXTVAL, :NEW.TAG_ID, 'Low Balance Alert - Balance: ' || :NEW.BALANCE, SYSDATE);
        DBMS_OUTPUT.PUT_LINE('LOW BALANCE WARNING for Tag ' || :NEW.TAG_ID);
    END IF;
END;
/

-- Auto-log admin actions
CREATE OR REPLACE TRIGGER TRG_ADMIN_LOG_ON_RECHARGE
AFTER INSERT ON ACCOUNT_RECHARGE
FOR EACH ROW
BEGIN
    INSERT INTO ADMIN_LOG (LOG_ID, ACTION_TYPE, ACTION_DETAIL, LOG_DATE)
    VALUES (
        ADMIN_LOG_SEQ.NEXTVAL,
        'RECHARGE',
        'Tag ' || :NEW.TAG_ID || ' recharged with ' || :NEW.RECHARGE_AMOUNT,
        SYSTIMESTAMP
    );
END;
/

-- Prevent negative tag balance
CREATE OR REPLACE TRIGGER TRG_PREVENT_NEGATIVE_BALANCE
BEFORE UPDATE OF BALANCE ON TAG
FOR EACH ROW
BEGIN
    IF :NEW.BALANCE < 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Tag balance cannot be negative');
    END IF;
END;
/

-- Validate transaction toll amount
CREATE OR REPLACE TRIGGER TRG_VALIDATE_TRANSACTION
BEFORE INSERT ON TRANSACTION_HISTORY
FOR EACH ROW
BEGIN
    IF :NEW.TOTAL_AMOUNT < 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Transaction amount cannot be negative');
    END IF;
    IF :NEW.DISTANCE_TRAVELLED < 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Distance travelled cannot be negative');
    END IF;
END;
/



-- >>> FILE: sql\08_queries.sql

-- =========================================================
-- ONE TAG ONE NATION - SAMPLE QUERIES
-- Joins | GROUP BY | HAVING | Subqueries
-- =========================================================

-- ===================== INNER JOIN =====================
-- Users with their registered vehicles
SELECT U.NAME, U.CNIC, V.PLATE_NUMBER, VT.VEHICLE_CLASS
FROM USERS U
INNER JOIN VEHICLE V ON U.USER_ID = V.USER_ID
INNER JOIN VEHICLE_TYPE VT ON V.TYPE_ID = VT.TYPE_ID;

-- Tags with vehicle and owner details
SELECT U.NAME, V.PLATE_NUMBER, T.TAG_ID, T.BALANCE, T.STATUS
FROM TAG T
INNER JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
INNER JOIN USERS U ON T.USER_ID = U.USER_ID;

-- Toll plazas on motorways
SELECT M.MOTORWAY_NAME, H.HIGHWAY_NAME, TP.PLAZA_NAME, TP.MILE_NO
FROM MOTORWAY M
INNER JOIN HIGHWAY H ON M.MOTORWAY_ID = H.MOTORWAY_ID
INNER JOIN TOLL_PLAZA TP ON H.HIGHWAY_ID = TP.HIGHWAY_ID;

-- ===================== LEFT JOIN =====================
-- All users and their feedback (including users with no feedback)
SELECT U.NAME, U.EMAIL, F.COMMENTS, F.RATING
FROM USERS U
LEFT JOIN FEEDBACK F ON U.USER_ID = F.USER_ID;

-- All plazas and employees
SELECT TP.PLAZA_NAME, E.EMPLOYEE_NAME, E.DESIGNATION
FROM TOLL_PLAZA TP
LEFT JOIN EMPLOYEE E ON TP.PLAZA_ID = E.PLAZA_ID;

-- ===================== RIGHT JOIN =====================
SELECT P.PLAZA_NAME, E.EMPLOYEE_NAME, E.DESIGNATION
FROM EMPLOYEE E
RIGHT JOIN TOLL_PLAZA P ON E.PLAZA_ID = P.PLAZA_ID;

-- ===================== GROUP BY =====================
-- Count tags by status
SELECT STATUS, COUNT(*) AS TAG_COUNT
FROM TAG
GROUP BY STATUS;

-- Total toll revenue per plaza
SELECT TP.PLAZA_NAME, SUM(TH.TOTAL_AMOUNT) AS TOTAL_REVENUE, COUNT(*) AS TXN_COUNT
FROM TRANSACTION_HISTORY TH
JOIN TOLL_PLAZA TP ON TH.PLAZA_ID = TP.PLAZA_ID
GROUP BY TP.PLAZA_NAME;

-- Average rating per user
SELECT U.NAME, AVG(F.RATING) AS AVG_RATING, COUNT(F.FEEDBACK_ID) AS FEEDBACK_COUNT
FROM USERS U
JOIN FEEDBACK F ON U.USER_ID = F.USER_ID
GROUP BY U.NAME;

-- ===================== HAVING =====================
SELECT STATUS, COUNT(*)
FROM TAG
GROUP BY STATUS
HAVING COUNT(*) >= 1;

-- Plazas with more than 1 transaction
SELECT TP.PLAZA_NAME, COUNT(*) AS TXN_COUNT
FROM TRANSACTION_HISTORY TH
JOIN TOLL_PLAZA TP ON TH.PLAZA_ID = TP.PLAZA_ID
GROUP BY TP.PLAZA_NAME
HAVING COUNT(*) > 0;

-- Users with average rating >= 4
SELECT U.NAME, AVG(F.RATING) AS AVG_RATING
FROM USERS U
JOIN FEEDBACK F ON U.USER_ID = F.USER_ID
GROUP BY U.NAME
HAVING AVG(F.RATING) >= 4;

-- ===================== SUBQUERIES =====================
-- Tag with maximum balance
SELECT TAG_ID, BALANCE, STATUS
FROM TAG
WHERE BALANCE = (SELECT MAX(BALANCE) FROM TAG);

-- Vehicles owned by users in Punjab
SELECT PLATE_NUMBER, MODEL
FROM VEHICLE
WHERE USER_ID IN (
    SELECT USER_ID FROM USERS WHERE PROVINCE = 'Punjab'
);

-- Plazas on highways with surcharge > 0
SELECT PLAZA_NAME, LOCATION
FROM TOLL_PLAZA
WHERE HIGHWAY_ID IN (
    SELECT HIGHWAY_ID FROM HIGHWAY_UPDATE WHERE SURCHARGE > 0
);

-- Tags with balance below average
SELECT TAG_ID, BALANCE
FROM TAG
WHERE BALANCE < (SELECT AVG(BALANCE) FROM TAG);

-- ===================== COMPLEX QUERIES =====================
-- Full transaction report with entry/exit terminals
SELECT
    TH.TRANSACTION_ID,
    V.PLATE_NUMBER,
    TE.TERMINAL_NAME AS ENTRY_TERMINAL,
    TX.TERMINAL_NAME AS EXIT_TERMINAL,
    TH.DISTANCE_TRAVELLED,
    TH.BASE_TOLL,
    TH.SURCHARGE,
    TH.EXEMPTION_DISCOUNT,
    TH.TOTAL_AMOUNT
FROM TRANSACTION_HISTORY TH
JOIN TAG T ON TH.TAG_ID = T.TAG_ID
JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
LEFT JOIN TERMINAL TE ON TH.ENTRY_TERMINAL_ID = TE.TERMINAL_ID
LEFT JOIN TERMINAL TX ON TH.EXIT_TERMINAL_ID = TX.TERMINAL_ID;

-- User roles report
SELECT U.NAME, U.USERNAME, R.ROLE_NAME, UR.ASSIGNED_DATE
FROM USERS U
JOIN USER_ROLE UR ON U.USER_ID = UR.USER_ID
JOIN ROLE R ON UR.ROLE_ID = R.ROLE_ID;